module.exports = {
    RECEIVE_ITEMS: 'RECEIVE_ITEMS',
    NEW_ITEM: 'NEW_ITEM',
    CANCEL_ITEM: 'CANCEL_ITEM',
    EXTEND_ITEM: 'EXTEND_ITEM',
    SAVE_ITEM: 'SAVE_ITEM',
    REMOVE_ITEM: 'REMOVE_ITEM',
    EDIT_ITEM: 'EDIT_ITEM',
    RECEIVE_ITEM: 'RECEIVE_ITEM',
    UPDATE_ITEM: 'UPDATE_ITEM'
};